services:

  zjbrainscience-front:
    image: cnife/zjbrainscience-front:f911a54e4b0de9054840cd26d67d2536 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "80:80"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        delay: 3s

