version: "3.8"
services:

  platform:
    image: ${PLATFORM_IMAGE_TAG}
    ports:
      - "1919:80"
    environment:
      DATABASE_URL: mysql+pymysql://zjlab:zjlab2022@database:3306/zj_brain_science_platform
      ALGORITHM_GRPC_ADDRESS: algorithm
      CACHE_HOST: cache
      CACHE_PORT: 6379
    volumes:
      - ~/log/ZJBrainSciencePlatform/app:/root/log/ZJBrainSciencePlatform/app
      - ~/data/ZJBrainSciencePlatform/file:/root/data/ZJBrainSciencePlatform/file
    depends_on:
      - database
      - cache
    deploy:
      replicas: ${PLATFORM_REPLICAS}
      restart_policy:
        condition: on-failure
        delay: 3s


  database:
    image: ${DATABASE_IMAGE_TAG}
    environment:
      MYSQL_ROOT_PASSWORD: zjlab2022root
      MYSQL_USER: zjlab
      MYSQL_PASSWORD: zjlab2022
      MYSQL_DATABASE: zj_brain_science_platform
      TZ: Asia/Shanghai
    ports:
      - "8100:3306"
    volumes:
      - ~/mysql/ZJBrainSciencePlatform/data:/var/lib/mysql
      - ~/log/ZJBrainSciencePlatform/mysql:/var/log/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s

  cache:
    image: ${CACHE_IMAGE_TAG}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 3s


  algorithm:
    image: ${ALGORITHM_IMAGE_TAG}
    environment:
      DATABASE_URL: mysql+pymysql://zjlab:zjlab2022@database:3306/zj_brain_science_platform
    volumes:
      - ~/log/ZJBrainSciencePlatformAlgorithm/app:/root/log/ZJBrainSciencePlatformAlgorithm/app
      - ~/data/ZJBrainSciencePlatform/file:/root/data/ZJBrainSciencePlatform/file
    depends_on:
      - database
    deploy:
      replicas: ${ALGORITHM_REPLICAS}
      restart_policy:
        condition: on-failure
        delay: 3s
